name: prism
include:
  - path: compose.db.yml
services:
  intercept.prism:
    image: yendelevium/intercept-prism:latest
    ports:
      - 7000:7000
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?search_path=public

  soul.prism:
    image: yendelevium/soul-prism:latest
    ports:
      - 3000:3000
    environment:
      INTERCEPT_URL: http://intercept.prism:7000
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?search_path=public
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}