name: intercept.prism
include:
  - path: ../compose.db.yml
services:
  intercept.prism:
    build:
      context: .
      dockerfile: Dockerfile
      target: build-release-stage
    ports:
      - 7000:7000
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?search_path=public
