// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Span struct {
	ID           string
	TraceId      string
	SpanId       string
	ParentSpanId pgtype.Text
	Operation    string
	ServiceName  string
	StartTime    int64
	Duration     int64
	Status       pgtype.Text
	Tags         []byte
	CreatedAt    pgtype.Timestamp
}
