// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertSpan = `-- name: InsertSpan :exec
INSERT INTO "Span" ("id", "traceId", "spanId", "parentSpanId", "operation", "serviceName", "startTime", "duration", "status", "tags")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT ("traceId", "spanId") DO NOTHING
`

type InsertSpanParams struct {
	ID           string
	TraceId      string
	SpanId       string
	ParentSpanId pgtype.Text
	Operation    string
	ServiceName  string
	StartTime    int64
	Duration     int64
	Status       pgtype.Text
	Tags         []byte
}

func (q *Queries) InsertSpan(ctx context.Context, arg InsertSpanParams) error {
	_, err := q.db.Exec(ctx, insertSpan,
		arg.ID,
		arg.TraceId,
		arg.SpanId,
		arg.ParentSpanId,
		arg.Operation,
		arg.ServiceName,
		arg.StartTime,
		arg.Duration,
		arg.Status,
		arg.Tags,
	)
	return err
}
